name: HuHoBot Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  PLUGIN_NAME: HuHo_Bot
  RepoName: 'HuoHuas001/HuHoBot-BDS'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: copy files
      working-directory: ${{ github.workspace }}
      run: |
        mkdir output/
        mkdir output/${{env.PLUGIN_NAME}}/
        cp -f *.js output/${{env.PLUGIN_NAME}}/
        cp -f *.json output/${{env.PLUGIN_NAME}}/

      shell: bash

    - name: Pack Release
      working-directory: ${{ github.workspace }}
      if: startsWith(github.ref, 'refs/tags/')
      run: 
        Compress-Archive -Path output\${{ env.PLUGIN_NAME }}\ ${{ github.workspace }}\plugins.zip

    - name: Upload PLUGIN
      uses: actions/upload-artifact@v4
      with:
        name: HuHoBot-BDS-${{github.ref_name}}
        path: ${{ github.workspace }}\output\${{ env.PLUGIN_NAME }}

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body: 'RT'
        files: |
          ${{ github.workspace }}\plugins.zip
      env:
          GITHUB_REPOSITORY: ${{env.RepoName}}
